### ISSUE TITLE
Fix hamburger button with thin screen

### ISSUE THREAD

**Issue by sauln** [codeforgoodconf/black_holes#16]
If you decrease the width of the browser, the nav-bar automatically collapses into a hamburger button.  The hamburger button doesn't do anything though, so we can't access the navigation keys.

Fix the hamburger button is it creates a drop down navigation panel.

**Comment by missygerlach** [comment]
We now have a fully-functional hamburger that has real buttons and that actually do things !

**Comment by accua** [comment]
Nice!
